### ISSUE TITLE
Text under 'login' screen to indicate click needed

### ISSUE THREAD

**Issue by chm0t** [bartoqid/PAN-AF#3]
On 'login' screen, post text under PANW logo to say "Click to enter" to make it obvious that you have to click to log in :)

**Comment by bartoqid** [comment]
I thought that's the fun, figuring it out how to get to the next stage of the tool :)

**Comment by chm0t** [comment]
hah, built-in IQ test - sounds like a feature to me!

**Comment by bartoqid** [comment]
Not an issue, as per chm0t comment, this is a built-in IQ test :)
